version: "3"

services:
  db:
    image: mongo
    container_name: mongo_database
    restart: always
    ports:
      - ${DB_PORT}:27017

  app:
    build: .
    container_name: bradesco_api
    restart: always
    env_file: .env
    command: yarn start
    depends_on:
      - db
    links:
      - db
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/app
    